include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - unnecessary_new
    - unnecessary_this
    - prefer_single_quotes
    - avoid_print
    - always_declare_return_types
    - prefer_relative_imports
